Webserver/AuditSphere/AuditSphere/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core import views
from core.forms import LoginForm
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('logs/', include('logs.urls')),
    path('administration/', include('administration.urls')),
    path('monitor/', include('monitor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Webserver/AuditSphere/administration/urls.py
from django.urls import path
from . import views 
from django.urls import path, include

app_name = 'administration'

urlpatterns = [
   path('users/', views.list_users, name='users'),
    path('users/disable/<int:user_id>/', views.disable_user, name='disable_user'),
    path('users/enable/<int:user_id>/', views.enable_user, name='enable_user'),
    path('users/delete/<int:user_id>/', views.delete_user, name='delete_user'),
    path('users/create/', views.create_user, name='create_user'),
    path('users/edit/<int:user_id>/', views.edit_user, name='edit_user'),
]

Webserver/AuditSphere/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from .forms import LoginForm
from .forms import PasswordResetRequestForm, SetNewPasswordForm, LoginForm
from . import views
from .views import log_chart_data  # Import the view


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('log_chart_data/', log_chart_data, name='log_chart_data'),  # Add this line
    path('contact/', views.contact, name='contact'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.user_logout, name='logout'),
    

    # Password reset URL patterns
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='core/password_reset.html',
        email_template_name='core/password_reset_email.html',
        subject_template_name='core/password_reset_subject.txt',
        form_class=PasswordResetRequestForm,
        success_url=reverse_lazy('core:password_reset_done')  # Specify the success_url with namespace here
    ), name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='core/password_reset_done.html'
    ), name='password_reset_done'),

    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='core/password_reset_confirm.html',
        form_class=SetNewPasswordForm,
        success_url=reverse_lazy('core:password_reset_complete')  # Specify the success_url with namespace here
    ), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='core/password_reset_complete.html'
    ), name='password_reset_complete'),
]

Webserver/AuditSphere/logs/urls.py
from django.urls import path
from . import views

app_name = 'logs'

urlpatterns = [
    path('', views.index, name='index'),
]

Webserver/AuditSphere/monitor/urls.py
from django.urls import path
from .views import LogEntryList, manage_clients, delete_client, enable_client, disable_client, edit_client

app_name = 'monitor'

urlpatterns = [
    path('api/log/', LogEntryList.as_view(), name='log-entry-list'),
    path('clients/', manage_clients, name='clients'),
    path('clients/disable/<int:token_id>/', disable_client, name='disable_client'),
    path('clients/enable/<int:token_id>/', enable_client, name='enable_client'),
    path('clients/delete/<int:token_id>/', delete_client, name='delete_client'),
    path('clients/edit/<int:token_id>/', edit_client, name='edit_client'),

]

Webserver/AuditSphere/core/models.py
'''
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, Group, Permission
from django.db import models
from django.utils import timezone
import uuid


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    date_joined = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    email_verified = models.BooleanField(default=False)  # Field to track whether the user's email has been verified
    email_verification_token = models.UUIDField(default=uuid.uuid4, editable=False)  # Field to store the email verification token
    groups = models.ManyToManyField(Group, related_name='core_customuser_groups')
    user_permissions = models.ManyToManyField(Permission, related_name='core_customuser_permissions')

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']
    
    def enable_user(self):
        self.is_active = True 
        self.save()
    
    def disable_user(self):
        self.is_active = False
        self.save()

    def __str__(self):
        return self.email
'''

Webserver/AuditSphere/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.conf import settings  # Import settings
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm
from django.apps import apps
from django.core.exceptions import ValidationError


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-full py-4 px-6 rounded-xl text-gray-600'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl text-gray-600'
    }))
    
class PasswordResetRequestForm(PasswordResetForm):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={
            'placeholder': 'Your email address',
            'class': 'w-full py-4 px-6 rounded-xl text-gray-600'
        })
    )

class SetNewPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'placeholder': 'New password',
            'class': 'w-full py-4 px-6 rounded-xl text-gray-600'
        })
    )
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Repeat new password',
            'class': 'w-full py-4 px-6 rounded-xl text-gray-600'
        })
    )

Webserver/AuditSphere/core/views.py
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout, get_user_model
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models import Count
from django.http import JsonResponse
from monitor.models import LogEntry
from django.db.models.functions import TruncHour
from operator import itemgetter




def user_logout(request):
    logout(request)
    return redirect('core:index')

def contact(request):
    return render(request, 'core/contact.html')

@login_required
def get_log_data(request):
    end_date = timezone.now()
    start_date = end_date - timezone.timedelta(days=7)  # Last 7 days

    logs = LogEntry.objects.filter(
    when__range=[start_date, end_date],
    action__in=['Renamed', 'Moved', 'Created', 'Accessed', 'Removed', 'Owner Changed']
    ).annotate(hour=TruncHour('when')).values('hour', 'action', 'who').annotate(count=Count('id')).order_by('hour')


    # Organizing data for line chart
    line_data = {}
    for log in logs:
        hour = log['hour'].strftime('%Y-%m-%d %H:%M:%S')
        if hour not in line_data:
            line_data[hour] = {'Renamed': 0, 'Moved': 0, 'Created': 0, 'Accessed': 0, 'Removed': 0, 'Owner Changed': 0}
        line_data[hour][log['action']] += log['count']

    bar_data = {}
    for log in logs:
        who = log['who']
        if who not in bar_data:
            bar_data[who] = {'total': 0, 'actions': {'Renamed': 0, 'Moved': 0, 'Created': 0, 'Accessed': 0, 'Removed': 0, 'Owner Changed': 0}}
        bar_data[who]['total'] += log['count']
        bar_data[who]['actions'][log['action']] += log['count']

    # Sort the actions based on frequency for each user
    for user_data in bar_data.values():
        user_data['actions'] = dict(sorted(user_data['actions'].items(), key=itemgetter(1), reverse=True))

    return line_data, bar_data


@login_required
def index(request):
    line_chart_data, bar_chart_data = get_log_data(request)
    return render(request, 'core/index.html', {'chart_data': line_chart_data, 'bar_chart_data': bar_chart_data})

@login_required
def log_chart_data(request):
    data = get_log_data(request)
    return JsonResponse(data)

Webserver/AuditSphere/core/templates/core/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Language" content="en">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} AuditSphere</title>
    <script src="\media\static\3.4.1.js"></script>

    
</head>
<body class="font-sans bg-gray-900 text-white">
    <header class="bg-gray-900">
        <nav class="mx-auto max-w-7xl flex items-center justify-between px-6 py-4">
            <div class="flex flex-1">
                <a href="/" class="p-2">
                    <span class="sr-only">AuditSphere</span>
                    {% load static %}
                    <img class="h-8 w-auto" src="\media\static\AuditSphere.png" alt="AuditSphere">
                </a>
            </div>
            <div class="hidden lg:flex gap-8">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'core:index' %}" class="text-sm font-medium leading-5 text-white hover:text-gray-300">Home</a>
                    <a href="{% url 'logs:index' %}" class="text-sm font-medium leading-5 text-white hover:text-gray-300">Logs</a>                    
                    <div class="relative group">
                        <a href="#" class="text-sm font-medium leading-5 text-white hover:text-gray-300 flex items-center">
                            Administration
                            <span class="ml-2">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="h-5 w-5">
                                    <path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" />
                                </svg>
                            </span>
                        </a>
                        <ul class="absolute z-[1000] left-0 mt-1/2 hidden min-w-max list-none overflow-hidden rounded-lg bg-gray-800 text-white text-left text-base shadow-lg group-hover:block">
                            <li>
                                <a class="block w-full px-4 py-2 text-sm text-gray-200 hover:bg-gray-700" href="{% url 'administration:users' %}">Users</a>
                            </li>
                            <li>
                                <a class="block w-full px-4 py-2 text-sm text-gray-200 hover:bg-gray-700" href="{% url 'monitor:clients' %}">Clients</a>
                            </li>
                            <li>
                                <a class="block w-full px-4 py-2 text-sm text-gray-200 hover:bg-gray-700" href="{% url 'admin:index' %}">Admin Panel</a>
                            </li>
                        </ul>
                    </div>
                {% endif %}
            </div>
            <div class="hidden lg:flex flex-1 justify-end">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'core:logout' %}" class="text-sm font-medium leading-5 text-white hover:text-gray-300">Sign out</a>
                {% else %}
                    <a href="{% url 'core:login' %}" class="text-sm font-medium leading-5 text-white hover:text-gray-300">Login</a>
                {% endif %}
            </div>
        </nav>
    </header>
    <hr class="border-gray-700">
    <div class="container mx-auto px-4 py-6">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

Webserver/AuditSphere/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>The contact page</h1>
{% endblock %}

Webserver/AuditSphere/core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %}AuditSphere{% endblock %}

{% block content %}
<div style="width: 60%;">
    <h2>AuditSphere Log Actions</h2>

    <!-- Line Chart -->
    <canvas id="logChart"></canvas>

    <!-- Bar Chart -->
    <canvas id="barChart"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    const ctx = document.getElementById('logChart').getContext('2d');
    const chartData = {{ chart_data|safe }};
    const hours = Object.keys(chartData);

    const dataSets = [];
    const actions = ['Renamed', 'Moved', 'Created', 'Accessed', 'Removed', 'Owner Changed'];  // List of actions
    const colors = ['rgba(255, 99, 132, 1)', 'rgba(54, 162, 235, 1)', 'rgba(255, 206, 86, 1)', 'rgba(75, 192, 192, 1)', 'rgba(153, 102, 255, 1)', 'rgba(54, 162, 235, 1)'];  // Colors for each action

    actions.forEach((action, index) => {
        const data = hours.map(hour => chartData[hour][action] || 0);
        dataSets.push({
            label: action,
            data: data,
            borderColor: colors[index],
            borderWidth: 2,
            fill: false
        });
    });

    new Chart(ctx, {
        type: 'line',
        data: {
            labels: hours,
            datasets: dataSets
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true,
                    grid: {
                        color: 'rgba(255, 255, 255, 0.1)'  // Add this line
                    },
                    ticks: {
                        color: 'rgba(255, 255, 255, 1)'
                    }
                },
                x: {
                    grid: {
                        color: 'rgba(255, 255, 255, 0.1)'  // Add this line
                    },
                    ticks: {
                        color: 'rgba(255, 255, 255, 1)'
                    }
                }
            },
            legend: {
                display: true,
                labels: {
                    color: 'rgba(255, 255, 255, 1)'
                }
            }
        }
    });

    // Bar Chart
    const barCtx = document.getElementById('barChart').getContext('2d');
    const barChartData = {{ bar_chart_data|safe }};
    const barLabels = Object.keys(barChartData);
    const barDataSets = [];

    // Rearrange the order of datasets based on the desired stacking
    const stackingOrder = ['Renamed', 'Moved', 'Removed', 'Created', 'Accessed', 'Owner Changed'];

    stackingOrder.forEach((action, index) => {
        const data = barLabels.map(who => barChartData[who]['actions'][action] || 0);
        barDataSets.push({
            label: action,
            data: data,
            backgroundColor: colors[actions.indexOf(action)],
            borderColor: 'rgba(255, 255, 255, 1)',  // Change this line
            borderWidth: 1
        });
    });

    new Chart(barCtx, {
        type: 'bar',
        data: {
            labels: barLabels,
            datasets: barDataSets
        },
        options: {
            indexAxis: 'y',
            scales: {
                x: {
                    stacked: true,
                    grid: {
                        color: 'rgba(255, 255, 255, 0.1)'  // Add this line
                    },
                    ticks: {
                        color: 'rgba(255, 255, 255, 1)'
                    }
                },
                y: {
                    stacked: true,
                    grid: {
                        color: 'rgba(255, 255, 255, 0.1)'  // Add this line
                    },
                    ticks: {
                        color: 'rgba(255, 255, 255, 1)'
                    }
                },
            },
            legend: {
                display: true,
                labels: {
                    color: 'rgba(255, 255, 255, 1)'
                }
            },
            tooltips: {
                mode: 'index',
                intersect: false,
            },
        },
    });
</script>
{% endblock %}

Webserver/AuditSphere/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block content %}
<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8 bg-gray-900 text-white">
  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <img class="mx-auto h-100 w-auto" src="\media\static\AuditSphere4.png" alt="AuditSphere Logo">
    <h2 class="text-center text-2xl font-bold leading-9 tracking-tight">Sign in to your account</h2>
  </div>

  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <form class="space-y-6" method="post" action=".">
      {% csrf_token %}
      
      {% if form.errors or form.non_field_errors %}
        <div class="text-red-500">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
      {% endif %}

      <div>
        <label for="id_email" class="block text-sm font-medium leading-6">Email address</label>
        <div class="mt-2">
          {{ form.username }}
        </div>
      </div>
      <div>
        <label for="id_password" class="block text-sm font-medium leading-6">Password</label>
        <div class="mt-2">
          {{ form.password }}
        </div>
      </div>
      <div>
        <button type="submit" class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-4 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Sign in</button>
      </div>
      <div class="text-sm ">
        <a href="{% url 'core:password_reset' %}" class=" font-semibold text-indigo-400 hover:text-indigo-300">Forgot password?</a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

Webserver/AuditSphere/core/templates/core/password_reset.html

{% extends 'core/base.html' %}
{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-800 rounded-xl">
        <h1 class="text-3xl font-semibold mb-6">Password reset</h1>
        <p>Enter your email address and we'll send you a link to reset your password.</p>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="mt-6 px-6 py-3 flex w-full justify-center rounded-md bg-indigo-600 px-3 py-4 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Send Mail</button>
        </form>
{% endblock %}

Webserver/AuditSphere/core/templates/core/password_reset_complete.html
{% extends 'core/base.html' %}
{% block content %}
  <h2>Password reset complete</h2>
  <p>Your password has been set. You can now <a href="{% url 'core:login' %}">log in</a>.</p>
{% endblock %}

Webserver/AuditSphere/core/templates/core/password_reset_confirm.html
{% extends 'core/base.html' %}
{% block content %}
  <h2>Enter new password</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700" type="submit">Change password</button>
  </form>
{% endblock %}

Webserver/AuditSphere/core/templates/core/password_reset_done.html
{% extends 'core/base.html' %}
{% block content %}
  <h2>Password reset</h2>
  <p>We've emailed you instructions for setting your password. If they haven't arrived in a few minutes, check your spam folder.</p>
{% endblock %}

Webserver/AuditSphere/core/templates/core/password_reset_email.html
Hello,

You're receiving this email because you requested a password reset for your user account at AuditSphere.

Please go to the following page and choose a new password:
{% url 'core:password_reset_confirm' uidb64=uid token=token %}
