Webserver/AuditSphere/AuditSphere/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core import views
from core.forms import LoginForm
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('logs/', include('logs.urls')),
    path('administration/', include('administration.urls')),
    path('monitor/', include('monitor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Webserver/AuditSphere/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from .forms import LoginForm
from .forms import PasswordResetRequestForm, SetNewPasswordForm, LoginForm
from . import views
from .views import log_chart_data  # Import the view


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('log_chart_data/', log_chart_data, name='log_chart_data'),  # Add this line
    path('contact/', views.contact, name='contact'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.user_logout, name='logout'),
    

    # Password reset URL patterns
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='core/password_reset.html',
        email_template_name='core/password_reset_email.html',
        subject_template_name='core/password_reset_subject.txt',
        form_class=PasswordResetRequestForm,
        success_url=reverse_lazy('core:password_reset_done')  # Specify the success_url with namespace here
    ), name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='core/password_reset_done.html'
    ), name='password_reset_done'),

    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='core/password_reset_confirm.html',
        form_class=SetNewPasswordForm,
        success_url=reverse_lazy('core:password_reset_complete')  # Specify the success_url with namespace here
    ), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='core/password_reset_complete.html'
    ), name='password_reset_complete'),
]

Webserver/AuditSphere/monitor/urls.py
from django.urls import path
from .views import LogEntryList, manage_clients, delete_client, enable_client, disable_client, edit_client

app_name = 'monitor'

urlpatterns = [
    path('api/log/', LogEntryList.as_view(), name='log-entry-list'),
    path('clients/', manage_clients, name='clients'),
    path('clients/disable/<int:token_id>/', disable_client, name='disable_client'),
    path('clients/enable/<int:token_id>/', enable_client, name='enable_client'),
    path('clients/delete/<int:token_id>/', delete_client, name='delete_client'),
    path('clients/edit/<int:token_id>/', edit_client, name='edit_client'),

]

Webserver/AuditSphere/monitor/models.py
from django.db import models
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
import uuid

class APIToken(models.Model):
    client = models.CharField(max_length=100, unique=True)
    token = models.UUIDField(default=uuid.uuid4, editable=False)
    is_active = models.BooleanField(default=True)  
    last_activity = models.DateTimeField(null=True, blank=True) 
    whitelisted_ips = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.client} - {self.token}"
    
    def is_ip_whitelisted(self, ip_address):
        if not self.whitelisted_ips:
            return True
        whitelisted_ips = [ip.strip() for ip in self.whitelisted_ips.split(',')]
        return ip_address in whitelisted_ips


class LogEntry(models.Model):
    when = models.DateTimeField()
    who = models.CharField(max_length=200)
    action = models.CharField(max_length=200)
    what = models.CharField(max_length=500, null=True)
    where = models.CharField(max_length=100)
    share_name = models.CharField(max_length=100, null=True)
    object_type = models.CharField(max_length=100)
    host = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    old_path = models.CharField(max_length=500, null=True)
    new_path = models.CharField(max_length=500, null=True)
    old_owner = models.CharField(max_length=500, null=True)
    new_owner = models.CharField(max_length=500, null=True)
    old_acl = models.CharField(max_length=5000, null=True)
    new_acl = models.CharField(max_length=5000, null=True)
    def __str__(self):
        return f"{self.when} - {self.who} - {self.action} - {self.what} - {self.where}"

Webserver/AuditSphere/monitor/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import LogEntry, APIToken
from .serializers import LogEntrySerializer
import uuid
import datetime


class LogEntryList(APIView):
    def post(self, request, format=None):
        data = request.data
        if isinstance(data, list):  # Check if incoming data is a list
            serializer = LogEntrySerializer(data=data, many=True)  # Set many=True for batch processing
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data, status=status.HTTP_201_CREATED)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        else:
            # Handle single log entry case (optional, based on your requirements)
            serializer = LogEntrySerializer(data=data)
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data, status=status.HTTP_201_CREATED)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@login_required
def manage_clients(request):
    if request.method == 'POST':
        client_name = request.POST.get('client_name')
        whitelisted_ips = request.POST.get('whitelisted_ips', '')
        client, created = APIToken.objects.get_or_create(client=client_name)

        # Update the whitelisted IPs if the client already exists or is newly created
        client.whitelisted_ips = whitelisted_ips
        client.save()

        if created:
            messages.success(request, f'Token generated for {client_name}.')
        else:
            messages.info(request, f'Client {client_name} updated.')

        return redirect('monitor:clients')

    clients = APIToken.objects.all()
    return render(request, 'monitor/manage_clients.html', {'clients': clients})

@login_required
def disable_client(request, token_id):
    api_token = get_object_or_404(APIToken, id=token_id)
    api_token.is_active = False
    api_token.save()
    return redirect('monitor:clients')

@login_required
def enable_client(request, token_id):
    api_token = get_object_or_404(APIToken, id=token_id)
    api_token.is_active = True
    api_token.save()
    return redirect('monitor:clients')

@login_required
def delete_client(request, token_id):
    api_token = get_object_or_404(APIToken, id=token_id)
    api_token.delete()
    return redirect('monitor:clients')

@login_required
def edit_client(request, token_id):
    api_token = get_object_or_404(APIToken, id=token_id)

    if request.method == 'POST':
        client_name = request.POST.get('client_name')
        whitelisted_ips = request.POST.get('whitelisted_ips', '')
        api_token.client = client_name
        api_token.whitelisted_ips = whitelisted_ips
        api_token.save()
        messages.success(request, f'Client {client_name} details updated.')
        return redirect('monitor:clients')

    return render(request, 'monitor/edit_client.html', {'api_token': api_token})

Webserver/AuditSphere/monitor/templates/monitor/edit_client.html
<!doctype html>
<html lang="en">
{% extends 'core/base.html' %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
{% block content %}

<div class="max-w-lg mx-auto py-6">
    <h2 class="text-2xl font-bold mb-4">Edit Client Details</h2>
    <form method="post">
        {% csrf_token %}
        <div>
            <label for="client-name" class="text-gray-300">Client Name:</label>
            <input type="text" name="client_name" id="client-name" aria-label="Client Name" class="bg-gray-900 w-full py-2 px-3 text-white border border-gray-500 rounded" value="{{ api_token.client }}">
        </div>
        <div>
            <label for="whitelisted_ips" class="text-gray-300">Whitelisted IPs:</label>
            <input type="text" name="whitelisted_ips" id="whitelisted_ips" aria-label="Whitelisted IPs" class="bg-gray-900 w-full py-2 px-3 text-white border border-gray-500 rounded" value="{{ api_token.whitelisted_ips }}">
        </div>
        <div class="mt-4">
            <button type="submit" name="action" value="update" class="flex w-full justify-center rounded-md bg-indigo-600 px-2 py-3 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Update</button>
        </div>
    </form>
</div>
</html>
{% endblock %}

Webserver/AuditSphere/monitor/templates/monitor/manage_clients.html
{% extends 'core/base.html' %}


{% block content %}
    <h2 class="text-2xl font-bold mb-4">Register New Client</h2>
    <form method="post" class="mb-4">
        {% csrf_token %}
        <div class="flex flex-wrap -mx-3 mb-6">
            <!-- New Client Name Input -->
            <div class="w-full md:w-1/3 px-3 mb-4 md:mb-0">
                <input class="appearance-none block w-full bg-gray-900 text-gray-400 border border-gray-500 rounded py-1.5 px-4 leading-tight" id="client-name" type="text" name="client_name" placeholder="New Client Name">
            </div>
            <!-- Whitelisted IPs Input -->
            <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <input class="appearance-none block w-full bg-gray-900 text-gray-400 border border-gray-500 rounded py-1.5 px-4 leading-tight" id="whitelisted_ips" type="text" name="whitelisted_ips" placeholder="Whitelisted IPs: Enter comma-separated IP addresses">
            </div>
            <!-- Submit Button -->
            <div class="px-3 mb-3 md:mb-0">
                <button type="submit" class="shadow bg-indigo-700 hover:bg-indigo-800 focus:shadow-outline focus:outline-none text-gray-100 font-bold py-1.5 px-4 rounded">
                    Create
                </button>
            </div>
        </div>
    </form>

    <table class="min-w-full divide-y divide-gray-200 shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <thead class="bg-gray-700">
            <tr>
                <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-100 uppercase tracking-wider">
                    Client Name
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-100 uppercase tracking-wider">
                    Last Activity
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-100 uppercase tracking-wider">
                    Token
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-100 uppercase tracking-wider">
                    Whitelisted IP
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-100 uppercase tracking-wider">
                    Actions
                </th>
            </tr>
        </thead>
        <tbody class="bg-gray-800 divide-y divide-gray-200">
            {% for client in clients %}
            <tr>
                <td class="px-6 py-4 whitespace-nowrap">{{ client.client }}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{ client.last_activity }}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{ client.token }}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{ client.whitelisted_ips }}</td>
                <td class="px-6 py-4 whitespace-nowrap">
                    {% if client.is_active %}
                        <a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded shadow-sm text-white bg-indigo-700 hover:bg-indigo-800" href="{% url 'monitor:disable_client' client.id %}">Deactivate</a>
                    {% else %}
                        <a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded shadow-sm text-white bg-indigo-700 hover:bg-indigo-800" href="{% url 'monitor:enable_client' client.id %}">Activate</a>
                    {% endif %}
                    <a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded shadow-sm text-white bg-indigo-700 hover:bg-indigo-800 ml-2" href="{% url 'monitor:delete_client' client.id %}">Delete</a>
                    <a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded shadow-sm text-white bg-indigo-700 hover:bg-indigo-800 ml-2" href="{% url 'monitor:edit_client' client.id %}">Edit</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}