Webserver/AuditSphere/AuditSphere/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core import views
from core.forms import LoginForm
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('logs/', include('logs.urls')),
    path('administration/', include('administration.urls')),
    path('monitor/', include('monitor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Webserver/AuditSphere/administration/urls.py
from django.urls import path
from . import views 
from django.urls import path, include

app_name = 'administration'

urlpatterns = [
   path('users/', views.list_users, name='users'),
    path('users/disable/<int:user_id>/', views.disable_user, name='disable_user'),
    path('users/enable/<int:user_id>/', views.enable_user, name='enable_user'),
    path('users/delete/<int:user_id>/', views.delete_user, name='delete_user'),
    path('users/create/', views.create_user, name='create_user'),
    path('users/edit/<int:user_id>/', views.edit_user, name='edit_user'),
]

Webserver/AuditSphere/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from .forms import LoginForm
from .forms import PasswordResetRequestForm, SetNewPasswordForm, LoginForm
from . import views
from .views import log_chart_data  # Import the view


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('log_chart_data/', log_chart_data, name='log_chart_data'),  # Add this line
    path('contact/', views.contact, name='contact'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.user_logout, name='logout'),
    

    # Password reset URL patterns
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='core/password_reset.html',
        email_template_name='core/password_reset_email.html',
        subject_template_name='core/password_reset_subject.txt',
        form_class=PasswordResetRequestForm,
        success_url=reverse_lazy('core:password_reset_done')  # Specify the success_url with namespace here
    ), name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='core/password_reset_done.html'
    ), name='password_reset_done'),

    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='core/password_reset_confirm.html',
        form_class=SetNewPasswordForm,
        success_url=reverse_lazy('core:password_reset_complete')  # Specify the success_url with namespace here
    ), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='core/password_reset_complete.html'
    ), name='password_reset_complete'),
]

Webserver/AuditSphere/administration/models.py
from django.db import models
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
import uuid

class APIToken(models.Model):
    client = models.CharField(max_length=100, unique=True)
    token = models.UUIDField(default=uuid.uuid4, editable=False)
    is_active = models.BooleanField(default=True)  
    last_activity = models.DateTimeField(null=True, blank=True) 

    def __str__(self):
        return f"{self.client} - {self.token}"

Webserver/AuditSphere/administration/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, SetPasswordForm
from django.core.exceptions import ValidationError

class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=30, 
        required=False, 
        widget=forms.TextInput(attrs={'placeholder': 'First Name'})
    )
    last_name = forms.CharField(
        max_length=30, 
        required=False, 
        widget=forms.TextInput(attrs={'placeholder': 'Last Name'})
    )
    username = forms.CharField(
        max_length=150, 
        widget=forms.TextInput(attrs={'placeholder': 'Username'})
    )
    email = forms.EmailField(
        max_length=254, 
        widget=forms.EmailInput(attrs={'placeholder': 'Email'})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'})
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'})
    )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'is_active')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("This email is already in use.")
        return email

class CustomUserChangeForm(UserChangeForm):
    first_name = forms.CharField(
        max_length=30, 
        required=False, 
        widget=forms.TextInput(attrs={'placeholder': 'First Name'})
    )
    last_name = forms.CharField(
        max_length=30, 
        required=False, 
        widget=forms.TextInput(attrs={'placeholder': 'Last Name'})
    )
    username = forms.CharField(
        max_length=150, 
        widget=forms.TextInput(attrs={'placeholder': 'Username'})
    )
    email = forms.EmailField(
        max_length=254, 
        widget=forms.EmailInput(attrs={'placeholder': 'Email'})
    )
    password1 = forms.CharField(
        label="New password",
        widget=forms.PasswordInput(attrs={'placeholder': 'New Password'}),
        required=False
    )
    password2 = forms.CharField(
        label="Confirm new password",
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirm New Password'}),
        required=False
    )

    class Meta(UserChangeForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if User.objects.filter(email=email).exclude(username=username).exists():
            raise ValidationError("This email is already in use.")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        if self.cleaned_data['password1']:
            user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

Webserver/AuditSphere/administration/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import CustomUserCreationForm, CustomUserChangeForm
from .models import APIToken

@login_required
def list_users(request):
    users = User.objects.all()
    return render(request, 'administration/list_users.html', {'users': users})

@login_required
def disable_user(request, user_id):
    user = get_object_or_404(User, id=user_id)
    user.is_active = False  # Disable the user
    user.save()
    return redirect('administration:users')

@login_required
def enable_user(request, user_id):
    user = get_object_or_404(User, id=user_id)
    user.is_active = True  # Enable the user
    user.save()
    return redirect('administration:users')

@login_required
def delete_user(request, user_id):
    user = get_object_or_404(User, id=user_id)
    user.delete()
    return redirect('administration:users')

@login_required
def create_user(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('administration:users')
    else:
        form = CustomUserCreationForm()
    return render(request, 'administration/create_user.html', {'form': form})

@login_required
def edit_user(request, user_id):
    user = get_object_or_404(User, id=user_id)
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('administration:users')
    else:
        form = CustomUserChangeForm(instance=user)
    return render(request, 'administration/edit_user.html', {'form': form, 'user_id': user_id})

Webserver/AuditSphere/administration/templates/Administration/create_user.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}

{% block content %}
  <div class="max-w-lg mx-auto py-6">
    <h2 class="text-2xl font-bold mb-4">Create User</h2>
    <form method="post">
      {% csrf_token %}
      {% for field in form %}
        <div class="mb-4">
          <label class="block text-white text-sm font-bold mb-2" for="{{ field.id_for_label }}">
            {{ field.label }}
          </label>
          {{ field|add_class:"bg-gray-900 w-full py-2 px-3 text-white border border-gray-500 rounded " }} 
          {% if field.help_text %}
            <p class="text-sm text-gray-600">{{ field.help_text }}</p>
          {% endif %}
          {% for error in field.errors %}
            <p class="text-red-500 text-xs italic">{{ error }}</p>
          {% endfor %}
        </div>
      {% endfor %}
      <div>
        <button type="submit" class="flex w-full justify-center rounded-md bg-indigo-600 px-2 py-3 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Create</button>
      </div>
    </form>
  </div>
{% endblock %}

Webserver/AuditSphere/administration/templates/Administration/edit_user.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}

{% block content %}
  <div class="max-w-lg mx-auto py-6">
    <h2 class="text-2xl font-bold mb-4">Edit User</h2>
    <form method="post">
      {% csrf_token %}
      {% for field in form %}
        {% if field.name != "password" %}
          <div class="mb-4">
            <label class="block text-white text-sm font-bold mb-2" for="{{ field.id_for_label }}">
              {{ field.label }}
            </label>
            {{ field|add_class:"bg-gray-900 w-full py-2 px-3 text-white border border-gray-500 rounded " }} 
            {% if field.help_text %}
              <p class="text-sm text-gray-600">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="text-red-500 text-xs italic">{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      {% endfor %}
      <div>
        <button type="submit" class="flex w-full justify-center rounded-md bg-indigo-600 px-2 py-3 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Update</button>
      </div>
    </form>
  </div>
{% endblock %}

Webserver/AuditSphere/administration/templates/Administration/list_users.html
{% extends 'core/base.html' %}

{% block content %}
<div class="flex justify-between items-center">
    <h2 class="text-2xl font-bold mb-4">Users</h2>
    <a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded shadow-sm text-white bg-indigo-700 hover:bg-indigo-800" href="{% url 'administration:create_user' %}">
        Create User &#x2b;
    </a>
</div>
<table class="min-w-full divide-y divide-gray-200 shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
    <thead class="bg-gray-700">
        <tr>
            <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-100 uppercase tracking-wider">
                Username
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-100 uppercase tracking-wider">
                First Name
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-100 uppercase tracking-wider">
                Last Name
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-100 uppercase tracking-wider">
                Email
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-100 uppercase tracking-wider">
                Last Login
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-100 uppercase tracking-wider">
                Actions
            </th>
        </tr>
    </thead>
    <tbody class="bg-gray-800 divide-y divide-gray-200">
        {% for user in users %}
        <tr>
            <td class="px-6 py-4 whitespace-nowrap">{{ user.username }}</td>
            <td class="px-6 py-4 whitespace-nowrap">{{ user.first_name }}</td>
            <td class="px-6 py-4 whitespace-nowrap">{{ user.last_name }}</td>
            <td class="px-6 py-4 whitespace-nowrap">{{ user.email }}</td>
            <td class="px-6 py-4 whitespace-nowrap">{{ user.last_login }}</td>
            <td class="px-6 py-4 whitespace-nowrap">
                {% if user.is_active %}
                    <a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded shadow-sm text-white bg-indigo-700 hover:bg-indigo-800" href="{% url 'administration:disable_user' user.id %}">Deactivate</a>
                {% else %}
                    <a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded shadow-sm text-white bg-indigo-700 hover:bg-indigo-800" href="{% url 'administration:enable_user' user.id %}">Activate</a>
                {% endif %}
                <a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded shadow-sm text-white bg-indigo-700 hover:bg-indigo-800 ml-2" href="{% url 'administration:delete_user' user.id %}">Delete</a>
                <a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded shadow-sm text-white bg-indigo-700 hover:bg-indigo-800 ml-2" href="{% url 'administration:edit_user' user.id %}">Edit</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}